name = "test_mathlib"
version = "0.1.0"
defaultTargets = ["test_mathlib"]

[[require]]
name = "mathlib"
git = "file:///D:/mathlib4-last_bump_for_v4.31.0"
rev = "v4.31.0-rc1"

[[lean_lib]]
name = "TestMathlib"

[[lean_exe]]
name = "test_mathlib"
root = "Main"
